apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: app
  newName: ghcr.io/vjp-anhlt-test/demo-ci-edit-src
  newTag: 93a179ae4307253b9bdef54dca9476a6dc49745b
